repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.4
  - hooks:
      - id: black
        args:
          - --line-length=99
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 23.3.0
  - hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
          - "--ignore=E203, E231, E501, W503, E402, E741"
          - "--exclude=./.venv"
          - "--max-complexity=21"
          - "--select=B,C,E,F,W,T4,B9"
    repo: https://github.com/pycqa/flake8
    rev: 6.0.0
  - hooks:
      - args:
          - --django
        id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0